language: julia
os:
    - linux
    - osx
julia:
    - 0.5
notifications:
    email: true
#script: # use the default script which does the following
#    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#    - julia -e 'Pkg.clone(pwd())';
#    - julia -e 'Pkg.build("JaynesCummings")';
#    - julia -e 'Pkg.test("JaynesCummings"; coverage=true)';
